### PR TITLE
Generate map for the EPL

### PR DESCRIPTION
**Pull request by obbers**
This lets you create a card to show the "map" of the data used by EPL.  
Screenshot 2024-01-16 100730

### CODE REVIEW

**Comment by jacconoordam** [comment]
Is it just downloading the Plotly graph and putting the code in  the visual editor?
And of couse changing the name/number.

**Comment by bikeymouse** [comment]
Nice card!  

However with the sensor in the normal position (with the usb-cable on the bottom side), the map, zones and movements are mirrored. From the point of view of the sensor, the x-axis on the right are the negative numbers and on the left the positive numbers. So with the this map, with the sensor on top facing "downwards", the left side should show the negative x-axis.

With this map that is reversed.

**Comment by EverythingSmartHome** [comment]
Hey, sorry it's taken sooooo long to get to this!

Thanks for the submission, was a great start. I went ahead and made a fix to make the perspective of the target to the sensor correct.

Also added logic so that if a user doesn't have zones 2-4 enabled (they are disabled by default) that the card still works and doesn't error.

Need to get this added to the docs but for now, looks great!

**Comment by mkothawala** [comment]
> Is it just downloading the Plotly graph and putting the code in the visual editor? And of couse changing the name/number. I get still a lot of errors so i must be doing something wrong :-( "Key 'entities.0.fn_var1' is not expected or not supported by the visual editor. Key 'entities.0.fn_var2' is not expected or not supported by the visual editor. Key 'entities.0.fn_var3' is not expected or not supported by the visual editor. Key 'entities.0.fn_var4' is not expected or not supported by the visual editor."

I'm having this same issue. This is what I get. If anyone figures out why this is happening, please let me know.

image

**Comment by obbers** [comment]
> **I figured out this error. I didn't have Zones 2-4 defined. Once I deleted those lines of code the map worked.**
> 
> > Is it just downloading the Plotly graph and putting the code in the visual editor? And of couse changing the name/number. I get still a lot of errors so i must be doing something wrong :-( "Key 'entities.0.fn_var1' is not expected or not supported by the visual editor. Key 'entities.0.fn_var2' is not expected or not supported by the visual editor. Key 'entities.0.fn_var3' is not expected or not supported by the visual editor. Key 'entities.0.fn_var4' is not expected or not supported by the visual editor."
> 
> I'm having this same issue. This is what I get. If anyone figures out why this is happening, please let me know.
> 
> image

Do you have any target entities disabled or renamed?  I can generate errors if I start disabling or renaming entities, specifically the X and Y entities.  Your entities should be named something like sensor.everything_presence_lite_2fbc58_target_2_y or sensor.everything_presence_lite_2fbc58_target_2_x

**Comment by tomas-dorda** [comment]
How do I make it work when the sensor is mounted upside down?

**Comment by AaronLayton** [comment]
I may be being dumb, but how do I add this card?

Is it meant to show up when  I `Add Card` ?

**Pull request merged**
