### PR TITLE
Fix-offline

### PR DESCRIPTION
**Pull request by dylan09**
Get the same error as in issue https://github.com/EverythingSmartHome/everything-presence-lite/issues/32#issue-1977845578.
Tried everything: no ble, disable improv, disable wifi power savings.

After all I changed code, so that `publish_state` is only called when sensor state has changed.
Don't know why that may cause the problem? But for me it is working for days without error.

### CODE REVIEW

**Comment by dylan09** [comment]
Done this change first only in the non-ble configuration. Maybe there are others, that can confirm its also working for them.
Then the changes could added to the ble version.

**Comment by M3te0r** [comment]
Hi @dylan09 @EverythingSmartHome I had the same offline/restart and HA publish issues with my own ESP32 - S2 Mini and a LD2450, modified the yaml with the changes from this PR, and it seems it's working better now
Consistent HA publish states and no disconnect

**Comment by xpenno255** [comment]
I've installed these updates onto 4 of my EPLites and will report back although initial feedback is positive. 

I did struggle to get everything uploaded and ended up having to remove the on_boot section of the config as I couldn't fix the various errors that I was getting with it. Not sure if that is critical or not. I did notice that I still see the uart took too long to respond messages but I don't think that's specifically related to the issue.

Thanks for your efforts, hopefully others will feedback and this could potentially get merged.

**Comment by xpenno255** [comment]
> > I've installed these updates onto 4 of my EPLites and will report back although initial feedback is positive.
> > I did struggle to get everything uploaded and ended up having to remove the on_boot section of the config as I couldn't fix the various errors that I was getting with it. Not sure if that is critical or not. I did notice that I still see the uart took too long to respond messages but I don't think that's specifically related to the issue.
> > Thanks for your efforts, hopefully others will feedback and this could potentially get merged.
> 
> The on_boot on this PR is misindented it should be inside the esphome section https://esphome.io/components/esphome.html?highlight=on_boot#on-boot

Thanks so much, I just updated successfully with the suggested edit 👍

**Comment by EverythingSmartHome** [comment]
Incorporated the changes into a new PR https://github.com/EverythingSmartHome/everything-presence-lite/pull/69 as some things had changed since this PR (my mistake) - thanks for submitting!

**Pull request closed without merging**
